/* eslint-disable no-template-curly-in-string */

import test from 'ava'
import convertFile from 'convert/file'

test('minimal', t => {
  const result = convertFile('test/material/2/minimal.json')
  t.is(result, `// No HTTP/HTTPS transactions have been recorded`)
})

test('request', t => {
  const result = convertFile('test/material/2/request.json')
  t.is(result, `// Auto-generated by the Load Impact converter

import http from "k6/http";

export let options = { maxRedirects: 4 };

export default function() {
  let res;

  res = http.get("http://example.com");
}
`)
})

test('raw body', t => {
  const result = convertFile('test/material/2/body-raw.json')
  t.is(result, `// Auto-generated by the Load Impact converter

import http from "k6/http";

export let options = { maxRedirects: 4 };

export default function() {
  let res;

  res = http.post("http://example.com", "line1\\nline2\\nline3\\n");
}
`)
})

test('form body', t => {
  const result = convertFile('test/material/2/body-form.json')
  t.is(result, `// Auto-generated by the Load Impact converter

import http from "k6/http";

export let options = { maxRedirects: 4 };

export default function() {
  let res;

  res = http.post("http://example.com", {
    first: "one",
    second: "two",
    third: "three"
  });
}
`)
})

test('url body', t => {
  const result = convertFile('test/material/2/body-url.json')
  t.is(result, `// Auto-generated by the Load Impact converter

import http from "k6/http";

export let options = { maxRedirects: 4 };

export default function() {
  let res;

  res = http.post(
    "http://example.com",
    { first: "one", second: "two", third: "three" },
    {
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      }
    }
  );
}
`)
})

test('variable', t => {
  const result = convertFile('test/material/2/variable.json')
  t.is(result, `// Auto-generated by the Load Impact converter

import http from "k6/http";

export let options = { maxRedirects: 4 };

export default function() {
  const vars = {
    domain: "example.com",
    machine: 573
  };

  let res;

  res = http.get(${'`http://${vars["machine"]}.${vars["domain"]}`'});
}
`)
})
