import test from 'ava'
import convertFile from 'convert/file'

test('v1', async t => {
  const [ main ] = await convertFile('test/material/1/format-v1.json')
  t.is(main, `// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import URI from "./libs/urijs.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  group("Test Folder 1", function() {
    group("Test Folder 2", function() {
      postman[Request]({
        name: "Test Request 2",
        method: "POST",
        address: "http://2.example.com/",
        data: {
          search: "puppies"
        },
        auth(config, Var) {
          const address = new URI(config.address);
          address.username("user456");
          address.password("secret2");
          config.address = address.toString();
          config.options.auth = "digest";
        }
      });
    });
  });

  group("Test Folder 3", function() {
    postman[Request]({
      name: "Test Request 3",
      method: "DELETE",
      address: "http://3.example.com/?type=cockroach&id=roach7",
      pre() {
        // Prepare for request
      },
      post(response) {
        // Test response
      }
    });
  });

  postman[Request]({
    name: "Test Request 1",
    method: "GET",
    address: "http://1.example.com/?search=kittens",
    headers: {
      Session: "abc123"
    },
    auth(config, Var) {
      const address = new URI(config.address);
      address.username("user123");
      address.password("secret");
      config.address = address.toString();
      config.options.auth = "basic";
    }
  });
}
`)
})

test('v2', async t => {
  const [ main ] = await convertFile('test/material/2/format-v2.json')
  t.is(main, `// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import URI from "./libs/urijs.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  group("Test Folder 1", function() {
    group("Test Folder 2", function() {
      postman[Request]({
        name: "Test Request 2",
        method: "POST",
        address: "http://2.example.com/",
        data: {
          search: "puppies"
        },
        auth(config, Var) {
          const address = new URI(config.address);
          address.username("user456");
          address.password("secret2");
          config.address = address.toString();
          config.options.auth = "digest";
        }
      });
    });
  });

  group("Test Folder 3", function() {
    postman[Request]({
      name: "Test Request 3",
      method: "DELETE",
      address: "http://3.example.com/?type=cockroach&id=roach7",
      pre() {
        // Prepare for request
      },
      post(response) {
        // Test response
      }
    });
  });

  postman[Request]({
    name: "Test Request 1",
    method: "GET",
    address: "http://1.example.com/?search=kittens",
    headers: {
      Session: "abc123"
    },
    auth(config, Var) {
      const address = new URI(config.address);
      address.username("user123");
      address.password("secret");
      config.address = address.toString();
      config.options.auth = "basic";
    }
  });
}
`)
})

test('v2.1', async t => {
  const [ main ] = await convertFile('test/material/2.1/format-v2.1.json')
  t.is(main, `// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import URI from "./libs/urijs.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  group("Test Folder 1", function() {
    group("Test Folder 2", function() {
      postman[Request]({
        name: "Test Request 2",
        method: "POST",
        address: "http://2.example.com/",
        data: {
          search: "puppies"
        },
        auth(config, Var) {
          const address = new URI(config.address);
          address.username("user456");
          address.password("secret2");
          config.address = address.toString();
          config.options.auth = "digest";
        }
      });
    });
  });

  group("Test Folder 3", function() {
    postman[Request]({
      name: "Test Request 3",
      method: "DELETE",
      address: "http://3.example.com/?type=cockroach&id=roach7",
      pre() {
        // Prepare for request
      },
      post(response) {
        // Test response
      }
    });
  });

  postman[Request]({
    name: "Test Request 1",
    method: "GET",
    address: "http://1.example.com/?search=kittens",
    headers: {
      Session: "abc123"
    },
    auth(config, Var) {
      const address = new URI(config.address);
      address.username("user123");
      address.password("secret");
      config.address = address.toString();
      config.options.auth = "basic";
    }
  });
}
`)
})
