import test from 'ava'
import convertFile from 'convert/file'

test('pre request', t => {
  const result = convertFile('test/material/2/pre-request.json')
  t.is(result, `// Auto-generated by the Load Impact converter

import "./postman-shim.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");

export default function() {
  postman[Request]({
    name: "TestRequest",
    method: "GET",
    address: "http://example.com",
    pre() {
      pm.variables.set("test", "a");
      pm.variables.set("test2", "b");
      pm.variables.set("test3", "c");
    }
  });
}
`)
})
