/* eslint-disable no-template-curly-in-string */

import test from 'ava'
import convertFile from 'convert/file'

test('global', t => {
  const result = convertFile('test/material/2/var-global.json', {
    globals: 'test/material/2/globals.json'
  })
  t.is(result, `// Auto-generated by the Load Impact converter

import "./postman-shim.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  global: {
    first: "one",
    second: "two",
    third: "three"
  }
});

export default function() {
  postman[Request]({
    name: "TestRequest",
    method: "GET",
    address: "http://{{first}}.{{third}}"
  });
}
`)
})

test('collection', t => {
  const result = convertFile('test/material/2/var-collection.json')
  t.is(result, `// Auto-generated by the Load Impact converter

import "./postman-shim.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  collection: {
    domain: "example.com",
    machine: 573
  }
});

export default function() {
  postman[Request]({
    name: "TestRequest",
    method: "GET",
    address: "http://{{machine}}.{{domain}}"
  });
}
`)
})

test('environment', t => {
  const result = convertFile('test/material/2/var-environment.json', {
    environment: 'test/material/2/environment.json'
  })
  t.is(result, `// Auto-generated by the Load Impact converter

import "./postman-shim.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  environment: {
    first: "one",
    second: "two",
    third: "three"
  }
});

export default function() {
  postman[Request]({
    name: "TestRequest",
    method: "GET",
    address: "http://{{first}}.{{third}}"
  });
}
`)
})

test('data json', t => {
  const result = convertFile('test/material/2/var-data-json.json', {
    json: 'test/material/2/data-json.json'
  })
  t.is(result, `// Auto-generated by the Load Impact converter

import "./postman-shim.js";

export let options = { maxRedirects: 4 };

const file = (() => {
  // Load data file
  const text = open("test/material/2/data-json.json");
  const rows = JSON.parse(text);
  return rows;
})();
options.iterations = file.length;

const Iteration = Symbol.for("iteration");
const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  data: file
});

export default function() {
  postman[Iteration]();

  postman[Request]({
    name: "TestRequest",
    method: "GET",
    address: "http://{{first}}.{{third}}"
  });
}
`)
})

test('data csv', t => {
  const result = convertFile('test/material/2/var-data-csv.json', {
    csv: 'test/material/2/data-csv.csv'
  })
  t.is(result, `// Auto-generated by the Load Impact converter

import "./postman-shim.js";
import papaparse from "./papaparse.js";

export let options = { maxRedirects: 4 };

const file = (() => {
  // Load data file
  const text = open("test/material/2/data-csv.csv");
  const rows = papaparse.parse(text, { header: true }).data;
  return rows;
})();
options.iterations = file.length;

const Iteration = Symbol.for("iteration");
const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  data: file
});

export default function() {
  postman[Iteration]();

  postman[Request]({
    name: "TestRequest",
    method: "GET",
    address: "http://{{first}}.{{third}}"
  });
}
`)
})

test('data custom iterations', t => {
  const result = convertFile('test/material/2/var-data-json.json', {
    json: 'test/material/2/data-json.json',
    iterations: 27
  })
  t.is(result, `// Auto-generated by the Load Impact converter

import "./postman-shim.js";

export let options = { maxRedirects: 4, iterations: 27 };

const file = (() => {
  // Load data file
  const text = open("test/material/2/data-json.json");
  const rows = JSON.parse(text);
  return rows;
})();

const Iteration = Symbol.for("iteration");
const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  data: file,
  iterations: 27
});

export default function() {
  postman[Iteration]();

  postman[Request]({
    name: "TestRequest",
    method: "GET",
    address: "http://{{first}}.{{third}}"
  });
}
`)
})
